openapi: 3.0.3
info:
  title: Customs Inventory Linking Imports
  contact: {}
  version: '1.0'
  description: |
    # Schemas and examples

    You can download the following zipped archive, which contains XML schemas and examples of the request and response payloads for each of the API endpoints:

    [Schemas and example messages](/api-documentation/docs/api/download/customs-inventory-linking-imports/1.0/inventory-linking-imports-schemas.zip)

    ZIP, 3.1MB last updated 17/09/2026
servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/
    description: Production
    variables: {}
tags:
  - name: Endpoints
    description: ''
paths:
  /customs/inventory-linking-imports/movement-validation:
    post:
      tags:
        - Endpoints
      summary: Inventory Linking Imports Validate Movement Response
      description: This validate movement response message is provided by the CSP as a result of a previous validate movement request. It represents the (positive/negative) outcome of matching a declaration Id (MRN) against the provided Inventory Consignment Reference (ICR)
      operationId: InventoryLinkingImportsValidateMovementResponse
      parameters:
        - name: Accept
          in: header
          description: Specifies the version of the API that you want to call. See [versioning](https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md).
          required: true
          style: simple
          schema:
            type: string
            example: application/vnd.hmrc.1.0+xml
        - name: Content-Type
          in: header
          description: Specifies the format of the request body. Must be "application/xml; charset=UTF-8" or the request will be rejected with HTTP status code 415.
          required: true
          style: simple
          schema:
            type: string
            example: application/xml; charset=UTF-8
        - name: X-Badge-Identifier
          in: header
          description: Represents the end-user who is interacting with the subscribed application. Must be 6 to 12 characters, consisting of any combination of numeric digits and/or upper-case letters.
          style: simple
          schema:
            type: string
            example: ABC123
        - name: X-Submitter-Identifier
          in: header
          description: The EORI associated with the originating owner of the declaration. Must have a maximum length of 17 characters, consisting of any combination of numeric digits and/or letters.
          style: simple
          schema:
            type: string
            example: GB123456789000
        - name: X-Correlation-ID
          in: header
          description: Alpha-numeric, maximum length is 36. Specifies the correlation id sent in the movement validation request. Returning the request correlation id in the movement validation response permits backend reconciliation of request and response.
          required: true
          style: simple
          schema:
            type: string
            example: ABC123
      responses:
        '202':
          description: ''
          headers: {}
          content:
            application/xml:
              schema:
                type: object
                xml:
                  namespace: http://gov.uk/customs/inventoryLinkingImport/v1
                  prefix: inv
                properties:
                  entryNumber:
                    type: string
                    xml:
                      prefix: inv
                  entryVersionNumber:
                    type: string
                    xml:
                      prefix: inv
                  inventoryConsignmentReference:
                    type: string
                    xml:
                      prefix: inv
                  irc:
                    type: string
                    xml:
                      prefix: inv
              examples:
                objectExample:
                  summary: An example InventoryLinkingImportsValidateMovementResponse
                  value: "<inv:InventoryLinkingImportsValidateMovementResponse xmlns:inv=\"http://gov.uk/customs/inventoryLinkingImport/v1\">\n\t<!--ID of the declaration assigned by Customs, being a specific customs ID or a Movement Reference Number (MRN)-->\n\t<inv:entryNumber>19GB9QRSR372ZFGVR4</inv:entryNumber>\n\t<!--Version number of the declaration before processing the amendment -->\n\t<inv:entryVersionNumber>1</inv:entryVersionNumber>\n\t<!--Inventory Consignment Reference number which matches that within the declaration payload MUCR-->\n\t<inv:inventoryConsignmentReference>GB/1234-:3333HB</inv:inventoryConsignmentReference>\n\t<!--001 indicates that the consignment has been mis-matched to the declaration which should cause CDS to stop processing the declaration further. -->\n\t<inv:irc>001</inv:irc>\n</inv:InventoryLinkingImportsValidateMovementResponse>\n"
        '400':
          description: ''
          headers: {}
          content:
            application/xml:
              schema:
                type: object
                xml: &ref_0
                  name: errorResponse
                properties: &ref_1
                  code:
                    type: string
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        message:
                          type: string
              examples:
                objectExample:
                  summary: A sample Resource
                  value: |
                    <errorResponse>
                      <code>BAD_REQUEST</code>
                      <message>Payload is not valid according to schema</message>
                      <errors>
                        <error>
                          <code>xml_validation_error</code>
                          <message>Error at line 13, column 13: no declaration found for element 'unknown'</message>
                        </error>
                      </errors>
                    </errorResponse>
        '403':
          description: ''
          headers: {}
          content:
            application/xml:
              schema:
                type: object
                xml: &ref_2
                  name: errorResponse
                properties: &ref_3
                  code:
                    type: string
                  message:
                    type: string
              examples:
                objectExample:
                  summary: A sample Resource
                  value: |
                    <errorResponse>
                      <code>PAYLOAD_FORBIDDEN</code>
                      <message>A firewall rejected the request</message>
                    </errorResponse>
        '500':
          description: ''
          headers: {}
          content:
            application/xml:
              schema:
                type: object
                xml: &ref_4
                  name: errorResponse
                properties: &ref_5
                  code:
                    type: string
                  message:
                    type: string
              examples:
                objectExample:
                  summary: A sample Resource
                  value: |
                    <errorResponse>
                      <code>INTERNAL_SERVER_ERROR</code>
                      <message>Internal server error</message>
                    </errorResponse>
      deprecated: false
      security:
        - userRestricted:
            - write:customs-il-imports-movement-validation
  /customs/inventory-linking-imports/arrival-notifications:
    post:
      tags:
        - Endpoints
      summary: Inventory Linking Imports Goods Arrival
      description: CSPs requesting to present their goods to Customs.
      operationId: InventoryLinkingImportsGoodsArrival
      parameters:
        - name: Accept
          in: header
          description: Specifies the version of the API that you want to call. See [versioning](https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md).
          required: true
          style: simple
          schema:
            type: string
            example: application/vnd.hmrc.1.0+xml
        - name: Content-Type
          in: header
          description: Specifies the format of the request body, which must be XML.
          required: true
          style: simple
          schema:
            type: string
            example: application/xml; charset=UTF-8
        - name: X-Badge-Identifier
          in: header
          description: Represents the end-user who is interacting with the subscribed application. Must be 6 to 12 characters, consisting of any combination of numeric digits and/or upper-case letters.
          style: simple
          schema:
            type: string
            example: ABC123
        - name: X-Submitter-Identifier
          in: header
          description: The EORI associated with the originating owner of the declaration. Must have a maximum length of 17 characters, consisting of any combination of numeric digits and/or letters.
          style: simple
          schema:
            type: string
            example: GB123456789000
      responses:
        '202':
          description: ''
          headers: {}
          content:
            application/xml:
              schema:
                type: object
                xml:
                  namespace: http://gov.uk/customs/inventoryLinkingImport/v1
                  prefix: inv
                properties:
                  entryNumber:
                    type: string
                    xml:
                      prefix: inv
                  entryVersionNumber:
                    type: string
                    xml:
                      prefix: inv
                  inventoryConsignmentReference:
                    type: string
                    xml:
                      prefix: inv
              examples:
                objectExample:
                  summary: An example InventoryLinkingImportsGoodsArrivalResponse
                  value: "<inv:inventoryLinkingImportsGoodsArrival xmlns:inv=\"http://gov.uk/customs/inventoryLinkingImport/v1\">\n\t<!--ID of the declaration assigned by Customs, being a specific customs ID or a Movement Reference Number (MRN)-->\n\t<inv:entryNumber>19GB9QWJDL941FGVR9</inv:entryNumber>\n\t<!-- Version number of the declaration before processing the amendment -->\n\t<inv:entryVersionNumber>2</inv:entryVersionNumber>\n\t<!-- Inventory Consignment Reference number which matches that within the declaration payload MUCR -->\n\t<inv:inventoryConsignmentReference>GB/1234-:3333HB</inv:inventoryConsignmentReference>\n</inv:inventoryLinkingImportsGoodsArrival>\n"
        '400':
          description: ''
          headers: {}
          content:
            application/xml:
              schema:
                type: object
                xml: *ref_0
                properties: *ref_1
              examples:
                objectExample:
                  summary: A sample Resource
                  value: |
                    <errorResponse>
                      <code>BAD_REQUEST</code>
                      <message>Payload is not valid according to schema</message>
                      <errors>
                        <error>
                          <code>xml_validation_error</code>
                          <message>Error at line 13, column 13: no declaration found for element 'unknown'</message>
                        </error>
                      </errors>
                    </errorResponse>
        '403':
          description: ''
          headers: {}
          content:
            application/xml:
              schema:
                type: object
                xml: *ref_2
                properties: *ref_3
              examples:
                objectExample:
                  summary: A sample Resource
                  value: |
                    <errorResponse>
                      <code>PAYLOAD_FORBIDDEN</code>
                      <message>A firewall rejected the request</message>
                    </errorResponse>
        '500':
          description: ''
          headers: {}
          content:
            application/xml:
              schema:
                type: object
                xml: *ref_4
                properties: *ref_5
              examples:
                objectExample:
                  summary: A sample Resource
                  value: |
                    <errorResponse>
                      <code>INTERNAL_SERVER_ERROR</code>
                      <message>Internal server error</message>
                    </errorResponse>
      deprecated: false
      security:
        - userRestricted:
            - write:customs-il-imports-arrival-notifications
components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            write:customs-il-imports-movement-validation: write:customs-il-imports-movement-validation
            write:customs-il-imports-arrival-notifications: write:customs-il-imports-arrival-notifications
  schemas:
    400Response:
      type: object
      xml: *ref_0
      properties: *ref_1
